### ISSUE TITLE
Melde seg ut og melde seg av E-post funksjon

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#12]
Vi må få til en side hvor medlemmer kan melde seg ut og/eller ikke få tilsendt e-post (Uavhengig om de er medlemmer eller ikke). Et slags kontrollpanel for medlemmer uten en profil? Det kan vell bli fikset med e-mail godkjenninger. For eksempel, om noen ikke ønsker å motta e-poster fra Kodesonen så får de tilsendt en e-mail med en hyperlenke som melder de ut fra e-post lista. Samme går for de som lenger ikke ønsker å være medlem.

**Comment by sirasjad** [comment]
Overført til nettside-v2.
