### ISSUE TITLE
Klikke på "Bli medlem" under Om Oss siden i lav resolution

### ISSUE THREAD

**Issue by sirasjad** [kodesonen/nettside#15]
Når media queries kicker inn under Om Oss siden så overstyrer z-index på steam effekten til kaffekoppen navigation menyet.

**Comment by sirasjad** [comment]
@Danielskry Overført fra nettside-v1. Er dette fortsatt en bug?

**Comment by Danielskry** [comment]
@sirasjad dette er fikset nå som grafikken er blitt erstattet! Problemet var hvordan animasjonen bestod av 2 layers med grafikk, og hvordan dette var skrevet mtp. z-indeks i CSS.
