### ISSUE TITLE
Database backups

### ISSUE THREAD

**Issue by sirasjad** [kodesonen/nettside#16]
Lage en button i "Generelle innstillinger" for å ta backups av SQL databasen.

**Comment by Danielskry** [comment]
Denne er viktig

**Comment by Danielskry** [comment]
Jeg kan begynne å jobbe på denne. Vil at det skal være mulighet for å få SQL dump tilsendt på e-post også.

**Comment by sirasjad** [comment]
Overført til nettside-v2.
