### ISSUE TITLE
Copy/paste av kode fra Microsoft Word/etc. til Editor

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#18]
Jeg tenker det skal være mulig å copy/paste kode/tekst fra programmer som Microsoft Word i Editor uten at det skaper krøll. Per dags dato vil en copy av dette (fra Microsoft Word):
[https://i.gyazo.com/8a2fff93c07aebe21bc0065a646bc6cb.png](https://i.gyazo.com/8a2fff93c07aebe21bc0065a646bc6cb.png)
se ut som dette i Editor:
[https://i.gyazo.com/86a8a33044395ddcaf9afd215b062c43.png](https://i.gyazo.com/86a8a33044395ddcaf9afd215b062c43.png)
Må se litt mer på dette.

**Comment by sirasjad** [comment]
Skjer dette også om du kopierer fra en ren tekst editor? F.eks fra Notepad.

**Comment by Danielskry** [comment]
Skal se litt mer på denne!

**Comment by Danielskry** [comment]
> 
> 
> Skal se litt mer på denne!

Nei dette skjer ikke når man kopierer ren tekst fra Notepad til editor
