### ISSUE TITLE
Animere ting på nettsiden?

### ISSUE THREAD

**Issue by sirasjad** [kodesonen/nettside#22]
Hva tenker du om å animere små ting på nettsiden? Titles, figurer, kanskje tekst osv. Se på dette biblioteket: https://daneden.github.io/animate.css/

Jeg syns nettsiden blir mye mer "levende" med fade/bounce animasjoner, og det er også veldig lett å implementere. Kanskje ikke overdrive med animasjoner, men litt her og der skader ikke.

**Comment by Danielskry** [comment]
Ja dette fikser jeg! Har laget en god del slike animasjoner før i CSS3. Kan bruke noen av konseptene jeg har tidligere gjort. Kort fortalt gikk det ut på å bygge bilder på bilder og deretter animere enkelte av bildene, noe som skaper en god flyt og kontroll over når/hvor og hvor lenge noe skal forbli animert.
