### ISSUE TITLE
Breadcrumb under admin panel og kurskatalog?

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#24]
Hadde det vært bra å hatt breadcrumb under admin panel og kurskatalog kanskje? Rett under header.

**Comment by sirasjad** [comment]
Ja, det hadde faktisk vært kjekt. Fikser du UI så ordner jeg page tracking og backend? Alle sidene er satt opp med ID-er, så dette kan implementeres ganske kjapt.

**Comment by Danielskry** [comment]
@sirasjad da har jeg satt opp en UI for dette!

**Comment by sirasjad** [comment]
Ordner dette nå.

**Comment by sirasjad** [comment]
Fikset.
