### ISSUE TITLE
"Previous" og "Next" i bunnen av hvert innlegg

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#27]
Under hvert innlegg på kurskatalogen burde det vell være en slags "Previous" og "Next" knapp som tar deg tilbake eller videre i hvert innlegg? En slags dobbel lenka liste på innleggene. Vet ikke helt åssen det blir med URL her, men dette har du vell styr på @sirasjad?

**Comment by Danielskry** [comment]
Har nå gjort CSS for dette, trenger bare back-end gjort.

**Comment by sirasjad** [comment]
Starter på denne.

**Comment by sirasjad** [comment]
Fikset.
