### ISSUE TITLE
Kurskatalog kapitler

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#28]
Oppsettet til kurskatalogen er nå at alle innleggene ligger etter hverandre:
1.0 X
1.1 Y
....
2.1 Å
Uten at kapitlene brytes opp med "course_jump_break". Men her tenker jeg at det ville vært bra å endret strukturen for hvordan innleggene er id merka? F.eks.:
Kapittel 1:
1.0 X
1.1 Y
...
Kapittel 2:
2.1 Å

**Comment by sirasjad** [comment]
Ordner dette først.

**Comment by sirasjad** [comment]
@Danielskry Kan du lage en template for hvordan du ønsker at kurskatalogen skal se ut? Altså inndeling av kapitler osv.

**Comment by sirasjad** [comment]
Fikset.
