### ISSUE TITLE
Lage grafikk til Om Oss siden

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#30]
Trenger noe ny grafikk til Om Oss siden

**Comment by sirasjad** [comment]
Hva tenker du om vi har sånn runde bilder av oss i styret på "Om oss" siden? Ser ganske stilig ut.

Eksempel: http://samara.computer/531_adaptive/startbootstrap-master/startbootstrap-master/templates/round-about.html

**Comment by Danielskry** [comment]
Tenkte å implementere noe som det ja. Men jeg tenkte noe mer som dette: https://i.gyazo.com/6a0f2e940561d116926549e1bbde163b.png

Hva synes du?

**Comment by Danielskry** [comment]
Denne er nå fikset!
