### ISSUE TITLE
Caption under bilder under kurs kapitler

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#35]
Under kurs kapitler står det bare "Disse kapitlene er tilgjengelig innenfor dette emnet. Skriv noe mer tekst her!" på alle kursene. Her kan vi vell legge inn mulighet for å oppdatere denne teksten med noe nyttig tekst for kurset? Blant annet ved å gi admins/kursforfattere muligheten til å skrive om dette til å bli informasjon om kurset under "Legg til nytt kurs" på kursbehandler?

**Comment by sirasjad** [comment]
Overført til nettside-v2.
