### ISSUE TITLE
Fikse dropdown values

### ISSUE THREAD

**Issue by sirasjad** [kodesonen/nettside#41]
Gjøre sånn at en dropdown value blir satt ut ifra sql verdi. F.eks Endre medlemmer siden.

**Comment by Danielskry** [comment]
Ingenting her jeg trenger å gjøre?

**Comment by sirasjad** [comment]
@Danielskry Jeg fikser denne, er bare litt backend kode som må fikses på. Men trenger å fikse litt UI også på en annen side, som du kanskje kan se på. Skal opprette ny Issue snart.
