### ISSUE TITLE
SEO for innlegg på kurskatalog

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#42]
Tenker spesifikt på meta data for innlegg publisert på kurskatalog.

Her burde meta data automatisk bli generert utifra detaljene oppgitt i selve innlegget. F.eks. om et innlegg blir navngitt "X algoritme". Så burde <title>X algoritme</title> samt meta data for sosiale medier også bli generert.

**Comment by sirasjad** [comment]
Overført til nettside-v2.
