### ISSUE TITLE
Setup database tables & models from nettside-v1, and seed

### ISSUE THREAD

**Issue by StanlyLife** [kodesonen/nettside#46]
For å koble sammen views og models og fullføre hovedoppgavene for nettside-v2 så trenger jeg kopi av tablene i databasen til nettside-v1 med modeller.

Disse tablene må også bli seedet til en viss grad for å kjøre functional testing.

_____

Er dette noe du kunne ordnet @sirasjad ?

**Comment by sirasjad** [comment]
Ordner dette straks.

**Comment by sirasjad** [comment]
Har sett på databasen til nettside-v1 og det er veldig mye rot i tabell oppsettet. Jeg vil egentlig at vi rekonstruerer databasen med ny arkitektur, spesielt med tanke på kurskatalogen. 

Slik ser tabellene ut i dag:
- kursinnlegg
- kurskapitler
- kurskatalog
- logs
- medlemmer
- utfordringer

Av disse er det kun "medlemmer" og "utfordringer" som fortsatt er aktuelle (heter nå User.cs og Challenges.cs under Models), mens resten av tabellene er utdaterte. 

Jeg kan overføre alle columns fra "medlemmer" tabellen til User.cs (eller KodesonenUser.cs heter det nå), hvis denne fungerer nå. Ser at du la til ApiKey også.

**Comment by StanlyLife** [comment]
Fra discord:

> Den meste jobben ligger vel da i å mappe databasen med columns, men det er vel en del av ER-diagrammet. Når det er fikset så kan jeg egt bare fikse modellene, men er ikke 100% på å seede så det måtte du evt fikset i såfall. @oysteinlondal  fikser ER-diagram når han har tid
