### ISSUE TITLE
Pene URL

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside#46]
Trenger pen URL. 

Fra dette:
?side=hjem
Til dette:
/hjem/

Kan gjøre dette gjennom .htaccess+php?

**Comment by sirasjad** [comment]
@Danielskry Jeg har sett litt på dette tidligere og det er veldig tuklete å holde på med htaccess for å ordne URLs når hele nettsiden vår er basert på PHP GET. Jeg tenker heller at vi ordner pene URLs når vi lager v2.0 av nettsiden basert på ASP.NET, for da løses dette problemet automatisk. Tanker?

**Comment by Danielskry** [comment]
Hmmm, du har nok rett!
